language: none

sudo: true
dist: bionic

install:
  - sudo apt-get --yes install snapd
  - sudo snap install hugo --channel=extended/stable
  - sudo apt-get install python3-pygments
  - git clone --recursive -j8 https://github.com/codefordus/codefordus.github.io.hugo.git
  - cd codefordus.github.io.hugo

script:
  - /snap/bin/hugo
  - cd public
  - ls -la

deploy:
  repo: codefordus/codefordus.github.io
  target_branch: master
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  edge: true
  on:
    branch: master